### ISSUE TITLE
Live2d SDK 3.0

### ISSUE THREAD

**Issue by niyaoyao** [mzyy94/ARKit-Live2D#1]
Yuki MIZUNOさん、初めまして。niyaoyaoと申します。今はLive2Dを使ってIOSプロジェクトの開発中です。SDLを使わず、UIKitだけでLive2d SDK 3.0 をインポートする方法はありませんか。突然の質問申し訳ないですが、ご教授頂けると幸いです。

**Comment by mzyy94** [comment]
Live2D Cubism SDK 4.0 is supported in 2.0
