### ISSUE TITLE
PARAM_ANGLE_Xの変更について

### ISSUE THREAD

**Issue by daisuke8929** [mzyy94/ARKit-Live2D#2]
mzyy94さん　こんにちは
突然の質問失礼いたします。
ContentUpdater.swiftでPARAM_ANGLE_Zの値を変更している箇所がありますが、PARAM_ANGLE_XおよびPARAM_ANGLE_Yも変更したいのですが、その場合の計算方法をご教示いただきたいです。

**Comment by mzyy94** [comment]
Parameter control of ParamAngleX and ParamAngleY is implemented in version 2.0
