### ISSUE TITLE
achieve the green background

### ISSUE THREAD

**Issue by Yang-Xijie** [mzyy94/ARKit-Live2D#5]
Thanks for having created such a great and easy to use project!

I have successfully installed `ARKit-Live2D` on my iPad Pro (3rd gen, iOS 15.1) and it works well when cast my face to the live2d model on iPad.

However, when I clicked the `i` (on the top right corner) for `Live Broadcast`, the app got stuck - the button `i`cannot be clicked again. 

I also tried using OBS (v27.1.3) on macOS (12.0.1) to cast the screen of iPad. However, I cannot make the green background (what I achieved was just the screen mirroring with the gray background).

I wonder what `Live Broadcast` will do and how to achieve the alpha model (green background) in OBS as you shown in your post <https://www.mzyy94.com/blog/2020/02/25/virtual-bishoujo-meeting/>?

![](https://www.mzyy94.com/assets/images/2020/02/25/obs-capture-device-iphone.png)

**Comment by Yang-Xijie** [comment]
Alright, I have found the option in `Settings` to **change background color** lol.

But I still don't know what are the functions of `Live Broadcast`...

**Comment by mzyy94** [comment]
Green screen can be removed with OBS function or Zoom option. Please google "OBS chroma key".
Live Broadcast feature means an extension for [ReplayKit](https://developer.apple.com/documentation/replaykit).
It's available in combination with ReplayKit-enabled Apps, such as YouTube, Mobcrush and so on.
